# ===== Configs principais via chart oficial =====
argo-cd:
  fullnameOverride: argocd

  server:
    configEnabled: true
    extraArgs: ["--insecure"] # exemplo; para produção, prefira TLS
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - argocd.dev.empresa.com
      paths:
        - /
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.dev.empresa.com

  configs:
    cm:
      url: https://argocd.dev.empresa.com
      timeout.reconciliation: 45s
      resource.customizations: |
        batch/Job:
          health.lua: |
            hs = {}
            if obj.status ~= nil then
              if obj.status.conditions ~= nil then
                for _, condition in ipairs(obj.status.conditions) do
                  if condition.type == "Complete" and condition.status == "True" then
                    hs.status = "Healthy"
                    hs.message = "Job completo"
                    return hs
                  end
                  if condition.type == "Failed" and condition.status == "True" then
                    hs.status = "Degraded"
                    hs.message = "Job falhou"
                    return hs
                  end
                end
              end
            end
            hs.status = "Progressing"
            hs.message = "Job em progresso"
            return hs

    rbac:
      policy.default: role:readonly
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        g, devs, role:readonly

    params:
      server.insecure: "true"
      controller.status.processors: "20"
      repo.server.parallelism.limit: "0"

  # Repositórios privados/registries via Secrets gerenciados abaixo
